#!/usr/bin/env bash
# Rename current tmux session. If there's exactly 1 window whose name
# matches the old session name, rename that window too.
new_name="$1"
old_name=$(tmux display-message -p '#{session_name}')
win_count=$(tmux display-message -p '#{session_windows}')
win_name=$(tmux display-message -p '#{window_name}')

tmux rename-session -- "$new_name"

if [ "$win_count" -eq 1 ] && [ "$win_name" = "$old_name" ]; then
    tmux rename-window -- "$new_name"
fi
